language: node_js
os: linux
dist: bionic
node_js:
  - 12
cache:
  npm: true
jobs:
  include:
    - stage: Test
      script: yarn test
    - stage: Generate dist and test
      if: tag IS blank
      script: yarn build && yarn run test-dist
    - stage: Generate dist, test and publish to GitHub
      if: tag IS present
      script:
        - yarn build && yarn run test-dist && git clone https://${GH_TOKEN}@github.com/gautamkrishnar/blog-post-workflow.git publish-repo  > /dev/null 2>&1 && cp -fv ./dist/blog-post-workflow.js ./publish-repo/dist/blog-post-workflow.js && cd publish-repo && git add ./dist/blog-post-workflow.js && git commit -m "Published ${TRAVIS_TAG}" && git push --quiet
