name: Build and test
on: [push, pull_request]
jobs:
  test:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    name: Generate build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn install
      - run: yarn test
      - run: yarn build && yarn run test-dist
